/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadingReadingIdRouteImport } from './routes/reading/$readingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingReadingIdRoute = ReadingReadingIdRouteImport.update({
  id: '/reading/$readingId',
  path: '/reading/$readingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reading/$readingId': typeof ReadingReadingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reading/$readingId': typeof ReadingReadingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reading/$readingId': typeof ReadingReadingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reading/$readingId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reading/$readingId'
  id: '__root__' | '/' | '/reading/$readingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadingReadingIdRoute: typeof ReadingReadingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/$readingId': {
      id: '/reading/$readingId'
      path: '/reading/$readingId'
      fullPath: '/reading/$readingId'
      preLoaderRoute: typeof ReadingReadingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadingReadingIdRoute: ReadingReadingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
